### ISSUE TITLE
how can I run the demo? can you give me some advice?

### ISSUE THREAD

**Issue by itsagirl** [xiyinmsu/PlantVision#1]

**Comment by itsagirl** [comment]
Thanks for your kindly share ,but in this project I can't understand the 'inputPath' .plz tell me.

**Comment by xiyinmsu** [comment]
> Thanks for your kindly share ,but in this project I can't understand the 'inputPath' .plz tell me.

Hi, I have provided more details in the README. Please take a look and let me know if that is clear to you.

**Comment by xiyinmsu** [comment]
> Thanks for your kindly share ,but in this project I can't understand the 'inputPath' .plz tell me.

Hi, I have also added a demo to show how to run the code. Hope this can help.

**Comment by itsagirl** [comment]
Thanks for your help.
